#include "../src/babychess-dbg-test.cc"
#include "../src/constant.cc"
#include "../src/main.cc"
#include "../src/moveable.cc"
#include "../src/pointer.cc"
#include "../src/string.cc"
#include "../src/verbose.cc"
