#include "../src/babychess-test-line-reader.cc"
#include "../src/constant.cc"
#include "../src/line_reader.cc"
#include "../src/main.cc"
#include "../src/moveable.cc"
#include "../src/pointer.cc"
#include "../src/string.cc"
#include "../src/verbose.cc"
