/* 
 * Automatically generated by sh/write-strings 
 */ 

#ifndef STRINGS_HH
#define STRINGS_HH


#define  str_about 	 1
#define  str_add 	 2
#define  str_apply 	 3
#define  str_back 	 4
#define  str_board_colors 	 5
#define  str_board_hide_frame 	 6
#define  str_board_no_highlight_last 	 7
#define  str_board_turn_board 	 8
#define  str_board_tutor 	 9
#define  str_cancel 	 10
#define  str_clear 	 11
#define  str_edit 	 12
#define  str_edit_notation 	 13
#define  str_edit_notation_settings 	 14
#define  str_edit_position 	 15
#define  str_empty 	 16
#define  str_end 	 17
#define  str_ev_engine 	 18
#define  str_ev_pause 	 19
#define  str_ev_reply_0 	 20
#define  str_ev_reply_1 	 21
#define  str_ev_reply_2 	 22
#define  str_ev_re_start 	 23
#define  str_ev_settings 	 24
#define  str_ev_start_or_play 	 25
#define  str_export 	 26
#define  str_forward 	 27
#define  str_hide_side_bar 	 28
#define  str_insert_file 	 29
#define  str_interaction 	 30
#define  str_invert 	 31
#define  str_load 	 32
#define  str_login 	 33
#define  str_logout 	 34
#define  str_mirror 	 35
#define  str_new 	 36
#define  str_new_game 	 37
#define  str_notation 	 38
#define  str_ok 	 39
#define  str_open 	 40
#define  str_open_in_editor 	 41
#define  str_opening_alternative 	 42
#define  str_opening_edit 	 43
#define  str_opening_subvariation 	 44
#define  str_pause 	 45
#define  str_play_best 	 46
#define  str_properties 	 47
#define  str_remove 	 48
#define  str_remove_end 	 49
#define  str_resign 	 50
#define  str_save 	 51
#define  str_save_as 	 52
#define  str_seek 	 53
#define  str_show_comment 	 54
#define  str_show_evaluator 	 55
#define  str_show_fen 	 56
#define  str_show_legal 	 57
#define  str_show_legal_list 	 58
#define  str_start 	 59
#define  str_take_back 	 60
#define  str_variation_leave 	 61
#define  str_variation_make_main 	 62
#define  str_variation_make_parent 	 63
#define  str_variation_remove 	 64

#define s_about 	"about"
#define s_add 	"add"
#define s_apply 	"apply"
#define s_back 	"back"
#define s_board_colors 	"board_colors"
#define s_board_hide_frame 	"board_hide_frame"
#define s_board_no_highlight_last 	"board_no_highlight_last"
#define s_board_turn_board 	"board_turn_board"
#define s_board_tutor 	"board_tutor"
#define s_cancel 	"cancel"
#define s_clear 	"clear"
#define s_edit 	"edit"
#define s_edit_notation 	"edit_notation"
#define s_edit_notation_settings 	"edit_notation_settings"
#define s_edit_position 	"edit_position"
#define s_empty 	"empty"
#define s_end 	"end"
#define s_ev_engine 	"ev_engine"
#define s_ev_pause 	"ev_pause"
#define s_ev_reply_0 	"ev_reply_0"
#define s_ev_reply_1 	"ev_reply_1"
#define s_ev_reply_2 	"ev_reply_2"
#define s_ev_re_start 	"ev_re_start"
#define s_ev_settings 	"ev_settings"
#define s_ev_start_or_play 	"ev_start_or_play"
#define s_export 	"export"
#define s_forward 	"forward"
#define s_hide_side_bar 	"hide_side_bar"
#define s_insert_file 	"insert_file"
#define s_interaction 	"interaction"
#define s_invert 	"invert"
#define s_load 	"load"
#define s_login 	"login"
#define s_logout 	"logout"
#define s_mirror 	"mirror"
#define s_new 	"new"
#define s_new_game 	"new_game"
#define s_notation 	"notation"
#define s_ok 	"ok"
#define s_open 	"open"
#define s_open_in_editor 	"open_in_editor"
#define s_opening_alternative 	"opening_alternative"
#define s_opening_edit 	"opening_edit"
#define s_opening_subvariation 	"opening_subvariation"
#define s_pause 	"pause"
#define s_play_best 	"play_best"
#define s_properties 	"properties"
#define s_remove 	"remove"
#define s_remove_end 	"remove_end"
#define s_resign 	"resign"
#define s_save 	"save"
#define s_save_as 	"save_as"
#define s_seek 	"seek"
#define s_show_comment 	"show_comment"
#define s_show_evaluator 	"show_evaluator"
#define s_show_fen 	"show_fen"
#define s_show_legal 	"show_legal"
#define s_show_legal_list 	"show_legal_list"
#define s_start 	"start"
#define s_take_back 	"take_back"
#define s_variation_leave 	"variation_leave"
#define s_variation_make_main 	"variation_make_main"
#define s_variation_make_parent 	"variation_make_parent"
#define s_variation_remove 	"variation_remove"

extern const char *string_list[]; 

#endif /* ! STRINGS_HH */

#ifdef STRINGS_DEFINE

const char *string_list[]={
NULL,
"about",
"add",
"apply",
"back",
"board_colors",
"board_hide_frame",
"board_no_highlight_last",
"board_turn_board",
"board_tutor",
"cancel",
"clear",
"edit",
"edit_notation",
"edit_notation_settings",
"edit_position",
"empty",
"end",
"ev_engine",
"ev_pause",
"ev_reply_0",
"ev_reply_1",
"ev_reply_2",
"ev_re_start",
"ev_settings",
"ev_start_or_play",
"export",
"forward",
"hide_side_bar",
"insert_file",
"interaction",
"invert",
"load",
"login",
"logout",
"mirror",
"new",
"new_game",
"notation",
"ok",
"open",
"open_in_editor",
"opening_alternative",
"opening_edit",
"opening_subvariation",
"pause",
"play_best",
"properties",
"remove",
"remove_end",
"resign",
"save",
"save_as",
"seek",
"show_comment",
"show_evaluator",
"show_fen",
"show_legal",
"show_legal_list",
"start",
"take_back",
"variation_leave",
"variation_make_main",
"variation_make_parent",
"variation_remove",

};

#endif /* STRINGS_DEFINE */
